### ISSUE TITLE
Unable to get data out of the Array!!!

### ISSUE THREAD

**Issue by kabilarajah** [gauravojha/shoppingcart-eloquent#1]
Thank you for this awesome cart which took away the stressful sessions out of the scenario, i tried creating a e-shop with the help of this Cart, and followed these.

    public function postCheckout(Request $request)
    {
        

         $order = new Order();
         
         $order->order = Cart::content();
         $order->name = Auth::user()->name;
         $order->user_id = Auth::user()->id;
         $order->table = $request->table;
         $order->save();

         Cart::emptyCart();

         return redirect('product');
     
    }

Then tried getting the data out of database using the following

    public function index()
    {
        $orders = Order::pluck('order');
       
        return view('order.index',compact('orders'));
    }

I can View the Orders stored in the column order of my table Orders, but the problem is i want to specifically get the details such as product_is, product_name out of the stored data unfortunately i get an output such as this,

Collection {#98 ▼ #items: array:2 [▼ 0 => "[{"id":31,"user_id":1,"product_id":2,"price":"10.00","qty":1,"product_name":"Two","imagepath":"https://placehold.it/640x480","price_per_item":"10.00","created_at":"2017-10-04 19:59:30","updated_at":"2017-10-04 19:59:30"},{"id":32,"user_id":1,"product_id":1,"price":"10.00","qty":1,"product_name":"One","imagepath":"https://placehold.it/640x480","price_per_item":"10.00","created_at":"2017-10-04 19:59:42","updated_at":"2017-10-04 19:59:42"}] ◀" 1 => "[{"id":33,"user_id":1,"product_id":1,"price":"10.00","qty":2,"product_name":"One","imagepath":"https://placehold.it/640x480","price_per_item":"10.00","created_at":"2017-10-04 20:29:58","updated_at":"2017-10-04 20:30:02"},{"id":34,"user_id":1,"product_id":2,"price":"10.00","qty":1,"product_name":"Two","imagepath":"https://placehold.it/640x480","price_per_item":"10.00","created_at":"2017-10-04 20:30:00","updated_at":"2017-10-04 20:30:00"}] ◀" ] }

how can i specifically get the certain data out of the Array?

**Comment by gauravojha** [comment]
@kabilarajah 

Hi, thanks for using this package. I am happy you liked it. 

I am not sure if this thread should be used, since the output you have mentioned seems more like how you are retrieving the records, rather than how the Cart is implemented. From what I understand, you completed a checkout and now the order is saved in the database in a Orders table in your database. 

If you use `pluck` then you retrieve a Collection. Instead I could suggest that you use the Eloquent framework so try something like 

`$existingOrders = Orders::orderBy('id', 'desc')->paginate(20);`

If I am correct, this will return you an array of Orders type, and not a Collection.

In your view, you can then create a foreach, and iterate through each using 

@foreach($orders as $order)
				<tr>
					
					<td><div align="center">{{ $order->id }}</div></td>
					<td><div align="center">{{ $order->product_id }}</div></td>

....
....
and so on.

Also,  I couldnt understand much from your code snippet above, as you are not using an order->id it seems.  So, it is possible with your code as well if you want to continue using Collections, but in your case, this is an array of arrays. So maybe try doing something like 

@foreach($orders as $order)
    @foreach($order as $individual_order_item)
        <td><div align="center">{{ $individual_order_item->id }}</div></td>
...
...

probably should work.

I would be closing this question as closed, because again, I dont think this is a drawback of the shopping cart, instead in the way you are accessing the stored data in your database. 

Hope this helped.
Gaurav
